<!DOCTYPE html>


<html>
    <head>
        WELCOME TO YOUR NEW SITE
    </head>
    <body>
    BRICOLOU HAS BEEN HACKED BY RICO & NAIL

    IF YOU WANT TO GET BACK YOUR WEBSITE WITH ALL ITS FILES, THESES ARE THE STEPS TO FOLLOW :

    - GIVE US A 20/20
    - DO NOT GIVE US ANY MORE DS IN TELECOMMUNICATIONS

    BYE !

    </body>